### ISSUE TITLE
关于放在eclipse中，目录很深的问题

### ISSUE THREAD

**Issue by zouzls** [mindwind/craft-atom#6]
你好大神，很激动能看到你写的这么短小精悍的Java轮子，刚刚导入到了我的eclipse中，准备研读研读，然后就发现一个小问题，如图：

![image](https://cloud.githubusercontent.com/assets/10088809/15463899/c45cb0e0-20fe-11e6-90c5-ea8693ddc009.png)

有可能是我使用工具不熟，但是我想往常一样调了一下package presentation，发现还是不行[汗]。。。
Google了一下发现不对，所以过来请教一下是啥原因，烦请大神告知，感激不尽。。。

email：zouzls@foxmail.com

**Comment by mindwind** [comment]
虽然我现在不怎么用 Eclipse 了，但我想说你的打开方式不对，maven 工程导入后直接会进入 package 路径

**Comment by zouzls** [comment]
多谢回复，我直接用的eclipse中的git导入的，另外：
你有用什么更好的工具吗？说说看呗，我也了解了解，多谢

**Comment by zouzls** [comment]
上面那个问题已经被我解决了，我就是换成maven的，不过莫名其妙出现了下面的这个问题（不好意思，maven用的不是特别熟，以前用gradle）：
![image](https://cloud.githubusercontent.com/assets/10088809/15491412/b213665a-21a2-11e6-8f32-276cfd4370ee.png)
每个pom.xml文件中都有报这个错。

**Comment by mindwind** [comment]
可以试试 IntelliJ IDEA
